services:

  web:
    image: nginx
    ports:
      - 85:80
    volumes:
      - '/home/skameika/project/candyshop/docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
      - '/home/skameika/project/candyshop:/var/www/html'

  php-fpm:
    build: '/home/skameika/project/candyshop/docker/php'
    volumes:
      - '/home/skameika/project/candyshop:/var/www/html'
      - './docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini'

  postgres:
    image: postgres
    volumes:
      - '/home/skameika/project/candyshop/docker/postgres/data:/var/lib/postgresql/data'
    ports:
      - 90:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}